### ISSUE TITLE
The parser doesn't seem to respect automatic semicolon insertion

### ISSUE THREAD

**Issue by kolmodin** [erikd/language-javascript#30]
In javascript, this code;

```javascript
var f = function() {
  return
  'value';
}
```

should be parsed like;

```javascript
var f = function() {
  return;
  'value';
}
```

The current parser seems to parse it as if the string ``'value'`` is part of the return statement, which it (somewhat surprisingly) is not.

**Comment by erikd** [comment]
Should be fixed in the above commit. Version 0.5.14.0 on Hackage.
