### ISSUE TITLE
Do while Loop without Block is not parsed

### ISSUE THREAD

**Issue by DFranzen** [erikd/language-javascript#35]
When I try to parse a do while loop with a single statement ending in ; like the following

do x=x+1; while(x<4);

I get a parser error

SemiColonToken {token_span = TokenPn 8 1 9, token_comment = [NoComment]}

, although it is executed correctly as JavaScript

**Comment by bmktuwien** [comment]
I  can confirm this bug too. Will this be fixed in near future?

-- cheers

**Comment by erikd** [comment]
I bit of experimentation with nodejs suggests that this problematic expression should be parsed as:

     do { x = x + 1 ; } while (x < 4) ;

Fixed in 45eeed837d1b3a.
