### ISSUE TITLE
Fails to parse foo.bar after break without semicolon

### ISSUE THREAD

**Issue by itchyny** [erikd/language-javascript#36]
It fails to parse the following code.
```javascript
var test = [];
for (var i = 0; i < 10; ++i) {
  if (false) break
  test.push(0)
}
```

**Comment by erikd** [comment]
If I insert a semicolon after the break, it parses file. Must be an issue with the `AutoSemi` insertion.

**Comment by erikd** [comment]
Spent some time tryng to fix this without any solution. Probably not fixable until the number of ambiguities in the grammar are reduced.

**Comment by itchyny** [comment]
Oh, that's a bad news for me. I know that semicolon insertion is one of a difficult specification for developers to implement a parser of javascript; I know because I've experienced implementation of a JavaScript parser some years ago. Semicolon insertion is one of terrible specifications in JavaScript, but there actually codes depending on this (https://github.com/feross/buffer/blob/master/index.js#L1363), I hope this bug fixed some day.

**Comment by erikd** [comment]
I have a solution! I've hacked the lexer to return an `AutoSemiToken` straight after `break`, `continue` or `return` if and only if the white space following those keywords contains a newline.

Currently cleaning up and adding tests.

**Comment by erikd** [comment]
Should be fixed in the above commit. Version 0.5.14 on hackage.

**Comment by itchyny** [comment]
Wow, thank you so much! I confirmed this bug is actually fixed now! Thank you!
