### ISSUE TITLE
Text support

### ISSUE THREAD

**Issue by cocreature** [erikd/language-javascript#37]
Currently only String seems to be supported, but for obvious reasons (performance, memory use) Text is often preferred, so it would be great if this package could support both.

**Comment by erikd** [comment]
Are you asking about input or output? For input, the use of the Alex as the lexer generator means I'm stuck with whatever Alex supports which I'm pretty sure is only `String`.

For the output (rendering) side, `blaze-builder` is used which easily allows both `ByeString` and `Text` output in addition to `String`/

**Comment by cocreature** [comment]
@erikd I was asking about input. Closing since it looks like there is nothing to make this possible.
