### ISSUE TITLE
cannot parse strings with certain allowed characters

### ISSUE THREAD

**Issue by michaelficarra** [erikd/language-javascript#42]
I ran into this issue using a literal ["escape" character](http://www.fileformat.info/info/unicode/char/001b/index.htm) (code point 27), which should be allowed within a string. The workaround for now is to use the `\x1B` escape sequence.

Ref. https://github.com/purescript/purescript/issues/1265

**Comment by erikd** [comment]
Fixed in both the `master` and `new-ast` branches in the above commits. The tests in the `new-ast` branch are much more extensive that the ones in the `master` branch.
