### ISSUE TITLE
Incorrect minification of bootstrap-datepicker

### ISSUE THREAD

**Issue by fgaray** [erikd/language-javascript#43]
In Firefox and Chrome it gives this error:
~~~
SyntaxError: expected expression, got keyword 'else'1 autogen-unjVjs7z.js:4:387
~~~ 

You can use this files to check it.

https://gist.github.com/fgaray/0a08a3f4ab3c01f2d7c9

I managed to get a minimal example:

~~~{.javascript}
if(1)
    ;
else if(2){
    3;
}
~~~

Incorrect result

~~~{.javascript}
if(1)else if(2)3
~~~

**Comment by erikd** [comment]
Yeah, this is one the classic ambiguous parse corner cases.

**Comment by erikd** [comment]
This was not in language-javascript but in hjsmin.

See https://github.com/erikd/hjsmin/issues/22
