### ISSUE TITLE
Cannot render correctly do while loop without braces

### ISSUE THREAD

**Issue by itchyny** [erikd/language-javascript#45]
This issue is related to #35, the library cannot render correctly.
```hs
import Language.JavaScript.Parser
main = print $ fmap renderToString $ parse "do x = x + 1; while (x < 4);" ""
```
```
Right "do x = x + 1  while (x < 4);"
```
The semicolon is dropped out and the result is an invalid JavaScript code.

**Comment by erikd** [comment]
Fixed and new version pushed to Hackage.

**Comment by itchyny** [comment]
Thank you so much for fixing so quickly!

**Comment by erikd** [comment]
You provided a really small example of what was going wrong which made it easy to fix.

Thank you.
