### ISSUE TITLE
Invalid RegEx Lexical Error

### ISSUE THREAD

**Issue by mrapogee** [erikd/language-javascript#47]
Compiler reports lexical error on column 73 for this line

`function Class(v) { return Object.prototype.toString.call(v).replace(/^\[object *|\]$/g, ''); }`

I've ran this line in multiple browsers and they seem to handle it fine.

**Comment by erikd** [comment]
Fixed in commit fcc6eceb21 and version 0.6.0.2 is on Hackage.
