### ISSUE TITLE
Add unicode escape parsing

### ISSUE THREAD

**Issue by teh** [erikd/language-javascript#48]
Strings like the following appear in some Purescript output. psc-bundle uses language-javascript for dead code elimination.

```
λ  readJs "a = '\u1234'"

<interactive>:7:16:
    lexical error in string/character literal at character 'u'
```

E.g.: from purescript-test-unit:

```
return Control_Monad_Eff_Class.liftEff(Control_Monad_Aff.monadEffAff (Test_Unit_Console.consoleLog("\u2713 Passed: " + l));
```

Chrome & Firefox parse this fine.

**Comment by erikd** [comment]
Fixed on `new-ast` branch. New version uploaded to Hackage.

Thanks!

**Comment by hdgarrood** [comment]
Am I right in thinking this issue can be closed now?

**Comment by erikd** [comment]
Yes, it can. Thanks.
