### ISSUE TITLE
0.6 on Stackage

### ISSUE THREAD

**Issue by srijs** [erikd/language-javascript#51]
Hi Erik!

When can we expect the 0.6.x branch on Stackage?

**Comment by erikd** [comment]
I've actually never used Stackage. I upload to Hackage.

**Comment by srijs** [comment]
Interesting, `language-javascript` is definitely listed on stackage as well:

https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L188

The way it works with stackage is that you still upload to hackage, but your package is picked up regularly if it's mentioned in the `build-constraints.yaml`, and bundled in the stackage definitions.

As it happens, the version that is pulled in to stackage nightly at the moment is still a 0.5.x.x version, because it is being artificially constrained:

https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L2168

This is the relevant issue: https://github.com/fpco/stackage/issues/1292, which also blocks never versions of `purescript` to enter stackage.

I was hoping someone (ideally the person who added it into stackage) could resolve the problem so we could enjoy the new 0.6 API.

**Comment by erikd** [comment]
Sorry, I can't help. You need to figure out who added it Stackage or how to add it yourself.

**Comment by srijs** [comment]
It says 'Alan Zimmerman' on the stackage entry, possibly @alanz?

**Comment by alanz** [comment]
There was a time when it was used by yesod (and possibly it still is), and I think @snoyberg added it as a dependency. Or I may have, back then. But I am no longer the maintainer, so if anyone has an interest in getting an updated version onto stackage they are welcome to make the PR, and change the maintainer name at the same time.

**Comment by erikd** [comment]
Yes. @alanz was the original author of language-javascript.

**Comment by erikd** [comment]
Yes, as @alanz says, the maintainer info should point to me.

**Comment by srijs** [comment]
That's great, @erikd. Stackage has a [social contract with maintainers](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md). To quote:

> This project is built around the concept of maintainers taking responsibility for making their packages work with the rest of the stable ecosystem, usually meaning the newest version of all dependencies.

Maintainership of a package naturally extends to maintainership of its stackage presence ;)

Since the old version of `language-javascript` on stackage currently prevents a number of packages from being updated to their newest version, it would be great if you see whether you can fix that problem.

**Comment by erikd** [comment]
There is nothing in that social contract that says that the upstream maintainer is the same as the Stackage maintainer.

I currently don't use Stackage and have no inclination to start using it just so I can be the Stackage maintainer.

However, if you want to be the Stakeage maintainer, you have my blessing. If at some stage I start using Stackage it might make sense for me to take over Stackage maintainership.

**Comment by erikd** [comment]
Closing this.
