### ISSUE TITLE
No space between `return` and identifier

### ISSUE THREAD

**Issue by srijs** [erikd/language-javascript#52]
Steps to reproduce:

- open repl
- import library (version 0.6.0.4)
- type `renderToString (JSAstStatement (JSReturn JSNoAnnot (Just (JSIdentifier
JSNoAnnot "foo")) (JSSemi JSNoAnnot)) JSNoAnnot)`

Expected outcome:

`"return foo;"`

Actual outcome:

`"returnfoo;"` (invalid javascript -- `ReferenceError: returnfoo is not defined`)

What is the correct construction of the AST to prevent this problem?

**Comment by srijs** [comment]
A possible workaround could be to always emit parenthesis around the argument to `return`.

**Comment by erikd** [comment]
If you want to render Javascript from hand constructed AST, you should run it through the minifier:

```
renderToString $ minifyJS (JSAstStatement (JSReturn JSNoAnnot (Just (JSIdentifier JSNoAnnot "foo")) (JSSemi JSNoAnnot)) JSNoAnnot)
```

`minifyJS` is in the `Langauge.Javascript.Process.Minify` module of `language-javasscript`.

**Comment by srijs** [comment]
Awesome, that worked! Thanks :)
