### ISSUE TITLE
Escaping quotes causes parser error

### ISSUE THREAD

**Issue by matsrietdijk** [erikd/language-javascript#53]
When trying to parse the following javascript code the parser returns an lexical error:

```
var a = '\"';
```

I know this `"` should not require escaping as it differs from the enclosing quotes, but it should not raise an error. The ecmascript5 specs say that `"` should be allowed as a [SingleEscapeCharacter](https://github.com/erikd/language-javascript/blob/master/ecmascript5.txt#L199).

This issues also happens the other way around (when escaping a `'` enclosed by `"`).

To add some context: I'm using this library to minify a vendor JS library which happens to use quotes this way. And as it seems the specs should allow this I'm creating this issue here. If I however misunderstood the specs please let me know and i will move the issue to the vendor library instead.

**Comment by erikd** [comment]
@alanz I fixed this on the train to work this morning. I'll commit it and push a new version to Hackage when I get home this afternooon.

**Comment by erikd** [comment]
Version 0.6.0.5 should now be on Hackage.

**Comment by matsrietdijk** [comment]
Thank you @erikd, for the quick response & fixing this issue!
