### ISSUE TITLE
Probably need Language.JavaScript.Parser.Token as exposed module

### ISSUE THREAD

**Issue by andre989** [erikd/language-javascript#57]
Hello,
First of all thanks for your precious and useful work on "language-javascript".
I'm quite new to Haskell development, so sorry in advance for any mistake I could do or noob question I could ask.

I'm working on a Haskell program, and I would need to manipolate the JSAST I'm getting from the parser, in order to further parse JSDoc comment annotations.

JSAnnot and CommentAnnotation are defined as:

```
data JSAnnot
    = JSAnnot !TokenPosn ![CommentAnnotation]
    | JSNoAnnot
    deriving (Data, Eq, Show, Typeable)

data CommentAnnotation
    = CommentA TokenPosn String
    | WhiteSpace TokenPosn String
    | NoComment
    deriving (Eq, Show, Typeable, Data, Read)
```

By the way, CommentAnnotation is defined inside Language.JavaScript.Parser.Token module and I'm not able to pattern match against it to extract the actual comment String because Language.JavaScript.Parser.Token is an hidden module.

As a matter of facts, when I try importing Language.JavaScript.Parser.Token I get the following error:

```
Could not find module ‘Language.JavaScript.Parser.Token’
    it is a hidden module in the package ‘language-javascript-0.6.0.8@langu_79vgAiOr5C496FlesUP4aI’
```

Would it be possible to expose Language.JavaScript.Parser.Token? Or how would you suggest to approach the problem? Any advice would be appreciated.
Thank you!

**Comment by erikd** [comment]
The type `CommentAnnotation` is re-exported by ` Language.JavaScript.Parser` which is in turn exported by `Language.Javascript` so it should be accessable just with that single export.

If I set up a new cabal sandbox and install the latest language-javascript (0.6.0.8) I can then compile and run the following program which uses `NoComment` which is one of the constructors of `CommentAnnotation`
```
import Language.JavaScript.Parser

main :: IO ()
main = print NoComment
```

**Comment by erikd** [comment]
Furthermore, `CommentAnnotation` show up here http://hackage.haskell.org/package/language-javascript-0.6.0.8/docs/Language-JavaScript-Parser.html#t:CommentAnnotation which suggests that you only need to import `Language.JavaScript.Parser` to access it.

**Comment by andre989** [comment]
Ops sorry, I didn't notice that.

Thank you a lot for your help!
