### ISSUE TITLE
Are there plans to support ES6 or/and ES7

### ISSUE THREAD

**Issue by phadej** [erikd/language-javascript#59]
both versions seems to be official: http://www.ecma-international.org/publications/standards/Ecma-262.htm

IIRC there aren't that much syntax changes.

**Comment by erikd** [comment]
No plans not to, its just that is not very high on my list of priorities.

**Comment by phadej** [comment]
@erikd So, could that be interpreted as, "if someone submits a patch, we'll help (advise / review) to get it eventually merged"?

**Comment by erikd** [comment]
Yes, you should interpret it like that.

**Comment by erikd** [comment]
Closing this in favor of #71 which explicitly list what is required and progress.
