### ISSUE TITLE
Lexer error for various escaped characters

### ISSUE THREAD

**Issue by pavonia** [erikd/language-javascript#60]
The lexer in version 0.6.0.9 breaks for inputs like `var x = "\/";`, complaining about an invalid character after the backslash. However, according to ecma-262 arbitrary Unicode characters (with some exceptions) may be escaped in string literals as stated in rule _NonEscapeCharacter_ of the string literal grammar. Several websites use this e.g. for escaping slashes in URLs.

**Comment by erikd** [comment]
@pavonia So looking at ECMA-262, 

```
NonEscapeCharacter ::
     SourceCharacter but not one of EscapeCharacter or LineTerminator
```
and
```
SourceCharacter ::
    any Unicode code unit
```
I'll see how easy this is to fix.

**Comment by erikd** [comment]
@pavonia Think I've fixed it. Please test.
