### ISSUE TITLE
Expose Language.JavaScript.Parser.StringEscape

### ISSUE THREAD

**Issue by glguy** [erikd/language-javascript#61]
It seems like Language.JavaScript.Parser.StringEscape was accidentally left unexposed. It's definitions are valuable to the library user, and they aren't even currently used by the package.

**Comment by erikd** [comment]
So you would like `unescapeString` and `unescapeRawString` exposed?

**Comment by glguy** [comment]
For context, it was being discussed in `#haskell` on Freenode that there wasn't any way to actually interpret string literals in this package. It seemed like that logic might have been held behind in this module. If that's not the case that these functions are appropriate for JavaScript then I suppose they shouldn't be exposed. Perhaps they should be removed then?

**Comment by erikd** [comment]
> If that's not the case that these functions are appropriate for JavaScript

I'm not sure if they are appropriate.

> Perhaps they should be removed then?

Considering that that are unused and untested, that may be the best option.

**Comment by erikd** [comment]
I'll release a new version in the next couple of days. Just waiting for feedback on #60.
